baseURL = 'http://taontech.top/'
languageCode = 'en-us'
title = '战'
theme = "hyde"

[params]
  description = "2022年度预测字"
  themeColor = "theme-base-09"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/taontech/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.cn/injobs/in/ning-tao-45a59933"}
  ]
